<?php

return [
    'superadmin' => [
        'dashboard',
        'analytics',
        'business_directory',
        'companies',
        'users',
        'roles',
        'permissions',
        'vcard_builder',
        'bio_link_builder',
        'contacts',
        'appointments',
        'calendar',
        'media',
        'campaigns',
        'plans',
        'plan_requests',
        'plan_orders',
        'coupons',
        'nfc_cards',
        'nfc_card_order_requests',
        'domain_requests',
        'currencies',
        'referral',
        'landing_page',
        'language',
        'addons',
        'google_wallet',
        'settings'
    ],
    
    'company' => [
        'dashboard',
        'analytics',
        'business_directory',
        'users',
        'roles',
        'vcard_builder',
        'bio_link_builder',
        'contacts',
        'appointments',
        'calendar',
        'media',
        'campaigns',
        'plans',
        'plan_requests',
        'plan_orders',
        'nfc_cards',
        'nfc_card_order_requests',
        'referral',
        'google_wallet',
        'settings'
    ]
];